# Generated by Django 6.0.1 on 2026-01-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crseed", "0007_auto_20220505_1133"),
    ]

    operations = [
        migrations.AddField(
            model_name="processparam",
            name="language",
            field=models.CharField(default="en-us", max_length=10),
        ),
        migrations.AddField(
            model_name="processparam",
            name="timezone",
            field=models.CharField(default="Europe/London", max_length=50),
        ),
        migrations.AlterField(
            model_name="processparam",
            name="fc_count",
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name="processparam",
            name="fc_interval",
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="processparam",
            name="max_size_difference",
            field=models.IntegerField(default=1024000),
        ),
    ]
